version: "3"
services:
    graphql-sever:
        command: yarn start:prod
        environment:
            NODE_ENV: prod
            PORT: 9000
            SUBSCRIPTION_PORT: 9001
            SUBSCRIPTION_ENDPOINT: "wss://ws-zditm-graphql.webjs.pl/subscriptions"
        deploy:
            labels:
                - 'traefik.backend.loadbalancer.sticky=true'
                - 'traefik.docker.network=proxy'
                - 'traefik.enable=true'
                - 'traefik.frontend.passHostHeader=true'
                - 'traefik.api.frontend.rule=HostRegexp:zditm-graphql.{domain:[a-z0-9-.]+}'
                - 'traefik.api.port=9000'
                - 'traefik.ws.frontend.rule=HostRegexp:ws-zditm-graphql.{domain:[a-z0-9-.]+}'
                - 'traefik.ws.port=9001'
            # tymczasowo
            # placement:
                # constraints: [node.role == worker]
            replicas: 1
            resources:
                limits:
                    cpus: '0.5'
                    memory: 500M
        image: zditm-graphql:prod
        networks:
            - proxy
        volumes:
            - ../:/app
    angular:
        deploy:
            labels:
                - 'traefik.docker.network=proxy'
                - 'traefik.enable=true'
                - 'traefik.frontend.rule=HostRegexp:findbus.{domain:[a-z0-9-.]+}'
                - 'traefik.port=80'
            replicas: 1
        image: zditm-graphql-client:prod
        networks:
            - proxy
networks:
    proxy:
        external:
            name: proxy
